services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    ports:
      - "9000:9000"
    tty: true
    stdin_open: true
    networks:
      - laravel_network
    depends_on:
      - nginx
      - db

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf      
    ports:
      - "8000:80"
    networks:
      - laravel_network

  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge

volumes:
  db_data: